In [84]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

### <B>Data Links</b>

In [85]:
crop_dataset="D:\Rajat thakur\Projects\DataArchive\Crop_recommendation.csv"
yields_dataset="D:\Rajat thakur\Projects\DataArchive\Crops_Yield_Dataset_Last20Years.csv"

## <b>Crop Recommendation System</b>

In [86]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,r2_score,confusion_matrix,classification_report

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

In [87]:
crop=pd.read_csv(crop_dataset)
crop.head()
# crop.size

      N     P     K  temperature   humidity        ph    rainfall label
0  90.0  42.0  43.0    20.879744  82.002744  6.502985  202.935536  rice
1  85.0  58.0  41.0    21.770462  80.319644  7.038096  226.655537  rice
2  60.0  55.0  44.0    23.004459  82.320763  7.840207  263.964248  rice
3  74.0  35.0  40.0    26.491096  80.158363  6.980401  242.864034  rice
4  78.0  42.0  42.0    20.130175  81.604873  7.628473  262.717340  rice

In [88]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6600 entries, 0 to 6599
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            6600 non-null   float64
 1   P            6600 non-null   float64
 2   K            6600 non-null   float64
 3   temperature  6600 non-null   float64
 4   humidity     6600 non-null   float64
 5   ph           6600 non-null   float64
 6   rainfall     6600 non-null   float64
 7   label        6600 non-null   object
dtypes: float64(7), object(1)
memory usage: 412.6+ KB

### <b>Label encoding</b>

In [89]:
encode=LabelEncoder()
crop['crop_encode']=encode.fit_transform(crop['label'])

In [90]:
crop

,N,P,K,temperature,humidity,ph,rainfall,label,crop_encode
0,90.00,42.00,43.00,20.879744,82.002744,6.502985,202.935536,rice,20
1,85.00,58.00,41.00,21.770462,80.319644,7.038096,226.655537,rice,20
2,60.00,55.00,44.00,23.004459,82.320763,7.840207,263.964248,rice,20
3,74.00,35.00,40.00,26.491096,80.158363,6.980401,242.864034,rice,20
4,78.00,42.00,42.00,20.130175,81.604873,7.628473,262.717340,rice,20
...,...,...,...,...,...,...,...,...,...
6595,101.22,27.89,24.00,27.776084,61.335484,6.912848,147.049740,coffee,5
6596,105.49,27.06,32.19,26.518875,54.147978,6.612705,187.434424,coffee,5
6597,97.21,18.24,28.93,23.353141,56.148733,7.499778,191.799184,coffee,5
6598,97.38,30.62,31.01,23.106477,63.742681,7.528885,129.714696,coffee,5
6599,102.69,32.95,26.27,25.560147,66.011555,6.586531,188.750682,coffee,5

In [91]:
mapping = {k: int(v) for k, v in zip(encode.classes_, encode.transform(encode.classes_))}
print(mapping)

{'apple': 0, 'banana': 1, 'blackgram': 2, 'chickpea': 3, 'coconut': 4, 'coffee': 5, 'cotton': 6, 'grapes': 7, 'jute': 8, 'kidneybeans': 9, 'lentil': 10, 'maize': 11, 'mango': 12, 'mothbeans': 13, 'mungbean': 14, 'muskmelon': 15, 'orange': 16, 'papaya': 17, 'pigeonpeas': 18, 'pomegranate': 19, 'rice': 20, 'watermelon': 21}

In [92]:
crop.columns

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label',
       'crop_encode'],
      dtype='object')

In [93]:
X=crop.drop(columns=['label','crop_encode'])
y=crop['crop_encode']

In [94]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [95]:
model1=RandomForestClassifier()
model1.fit(X_train,y_train)

RandomForestClassifier()

In [96]:
train_acc=model1.predict(X_train)
test_acc=model1.predict(X_test)

print("Train Accuracy: ",accuracy_score(y_train,train_acc))
print("Test Accuracy: ",accuracy_score(y_test,test_acc))

Train Accuracy:  1.0
Test Accuracy:  0.9916666666666667

In [97]:
print("Train Accuracy: ",classification_report(y_train,train_acc))

Train Accuracy:                precision    recall  f1-score   support

           0       1.00      1.00      1.00       238
           1       1.00      1.00      1.00       235
           2       1.00      1.00      1.00       248
           3       1.00      1.00      1.00       239
           4       1.00      1.00      1.00       234
           5       1.00      1.00      1.00       237
           6       1.00      1.00      1.00       247
           7       1.00      1.00      1.00       244
           8       1.00      1.00      1.00       243
           9       1.00      1.00      1.00       234
          10       1.00      1.00      1.00       240
          11       1.00      1.00      1.00       236
          12       1.00      1.00      1.00       238
          13       1.00      1.00      1.00       243
          14       1.00      1.00      1.00       241
          15       1.00      1.00      1.00       234
          16       1.00      1.00      1.00       226
          17       1.00      1.00      1.00       251
          18       1.00      1.00      1.00       229
          19       1.00      1.00      1.00       258
          20       1.00      1.00      1.00       234
          21       1.00      1.00      1.00       251

    accuracy                           1.00      5280
   macro avg       1.00      1.00      1.00      5280
weighted avg       1.00      1.00      1.00      5280

In [98]:
print("Test Accuracy: ",classification_report(y_test,test_acc))

Test Accuracy:                precision    recall  f1-score   support

           0       1.00      1.00      1.00        62
           1       1.00      1.00      1.00        65
           2       1.00      1.00      1.00        52
           3       1.00      1.00      1.00        61
           4       1.00      1.00      1.00        66
           5       1.00      1.00      1.00        63
           6       0.96      1.00      0.98        53
           7       1.00      1.00      1.00        56
           8       0.92      0.96      0.94        57
           9       1.00      1.00      1.00        66
          10       0.98      1.00      0.99        60
          11       1.00      0.95      0.98        64
          12       1.00      1.00      1.00        62
          13       0.98      0.98      0.98        57
          14       1.00      1.00      1.00        59
          15       1.00      1.00      1.00        66
          16       1.00      1.00      1.00        74
          17       1.00      1.00      1.00        49
          18       1.00      1.00      1.00        71
          19       1.00      1.00      1.00        42
          20       0.97      0.92      0.95        66
          21       1.00      1.00      1.00        49

    accuracy                           0.99      1320
   macro avg       0.99      0.99      0.99      1320
weighted avg       0.99      0.99      0.99      1320

In [99]:
test_samples = np.array([
    [90, 42, 43, 20.8, 82, 6.5, 202],   # rice-like
    [20, 30, 10, 25, 60, 6.0, 100],     # pulses
    [100, 50, 50, 27, 85, 6.3, 250]     # high rainfall crop
])

preds = model1.predict(test_samples)

print("Predictions (encoded):", preds)
print("Predicted crops:", encode.inverse_transform(preds))

Predictions (encoded): [20 16 20]
Predicted crops: ['rice' 'orange' 'rice']

In [100]:
test_samples = np.array([
    [90, 42, 43, 20.8, 82, 6.5, 202],   # rice-like
    [20, 30, 10, 25, 60, 6.0, 100],     # pulses
    [100, 50, 50, 27, 85, 6.3, 250]     # high rainfall crop
])

preds = model1.predict(test_samples)

print("Predictions (encoded):", preds)
print("Predicted crops:", encode.inverse_transform(preds))

Predictions (encoded): [20 16 20]
Predicted crops: ['rice' 'orange' 'rice']

In [101]:
test_samples = np.array([[11,122,195,12.14,83.568,5.6,69.63],	    #grapes
                        [89,85,49,28,84,5,109],	    #banana					
                        [2,19,39,20,87,5,109]	    #pomegranate
])

preds = model1.predict(test_samples)

print("Predictions (encoded):", preds)
print("Predicted crops:", encode.inverse_transform(preds))

Predictions (encoded): [ 7  1 19]
Predicted crops: ['grapes' 'banana' 'pomegranate']

In [102]:
test_samples = np.array([[],	    #grapes
                        [89,85,49,28,84,5,109],	    #banana					
                        [2,19,39,20,87,5,109]	    #pomegranate
])

preds = model1.predict(test_samples)

print("Predictions (encoded):", preds)
print("Predicted crops:", encode.inverse_transform(preds))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [ ]:
probs = model1.predict_proba([[
    100, 40, 50, 27.5, 85, 6.2, 220
]])

top3 = np.argsort(probs[0])[-3:][::-1]

for i in top3:
    print(encode.inverse_transform([i])[0], probs[0][i])

rice 0.6
banana 0.14
papaya 0.12

In [ ]:
crop.groupby('label')[['rainfall', 'humidity', 'temperature']].mean()

               rainfall   humidity  temperature
label
apple        112.977245  92.368181    22.630890
banana       104.950542  80.484697    27.462160
blackgram     68.064739  64.979958    29.939056
chickpea      79.435147  16.931807    18.919304
coconut      176.527156  94.841607    27.422199
coffee       157.661434  59.267344    25.370871
cotton        80.139025  80.008593    23.935226
grapes        69.828146  81.807725    23.475068
jute         175.245464  79.749201    24.965009
kidneybeans  107.178944  21.648526    20.256204
lentil        45.652518  64.815992    24.480534
maize         84.679588  65.437312    22.279236
mango         94.647306  50.154848    31.115810
mothbeans     52.044121  53.020277    28.274481
mungbean      47.980558  85.656313    28.550181
muskmelon     24.740025  92.456435    28.665975
orange       110.344265  92.199168    22.848752
papaya       143.246935  92.294000    34.083341
pigeonpeas   151.890036  47.863238    28.042036
pomegranate  107.543668  90.190060    21.756171
rice         237.582335  82.256280    23.866612
watermelon    50.616987  85.175047    25.642038

In [ ]:
# param_grid = {
#     "n_estimators": [200, 300, 500],
#     "max_depth": [10, 15, 20, None],
#     "min_samples_split": [2, 5, 10],
#     "min_samples_leaf": [1, 2, 4],
#     "max_features": ["sqrt", "log2"]
# }

In [ ]:
# from sklearn.model_selection import GridSearchCV

# grid = GridSearchCV(
#     RandomForestClassifier(random_state=42),
#     param_grid,
#     cv=5,
#     n_jobs=-1,
#     verbose=1
# )

# grid.fit(X_train, y_train)

# print("Best Params:", grid.best_params_)

In [ ]:
=